<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>GotifyClient</AssemblyName>
    <Version>1.1.0</Version>
    <Product>Gotify Windows Client</Product>
    <Description>Native Windows client for Gotify</Description>
    <ApplicationIcon>assets\gotify.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\gotify.ico" />
  </ItemGroup>

</Project>
